spring:
  application:
    name: Lost_And_Found

  datasource:
    url: jdbc:mysql://localhost:3306/lost_and_found_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Shiven@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false

  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false

server:
  port: 8080
